function []=runAll( dirName )
% usage dirName: raw data(directory has the bin file generated by usrp code)

figureDirName = dirName;
dataDir = dir( dirName );
%dataDir
isDir_index = [ dataDir(:).isdir ];
subDir = { dataDir(isDir_index).name }';
subDir( ismember( subDir, {'.', '..'} ) ) = [];
%subDir
subDir

for k=1:length(subDir)
    subDir(k)
    
    % dirName
    subDirName = sprintf( '%s/%s', dirName, char(subDir(k)) );
    
    % subDirName
    [resultDirName, errorFlag] = decode_run_all( subDirName );
    
    if( errorFlag==1 )
        continue;
    end
    
    %resultDirName = sprintf( '%s/result', subDirName );
    test_for_minus_DC_run_all( resultDirName );
end

%plotFigure( figureDirName );

end